name: Nightly

on:
  push:
    paths:
    - 'src/**'
    - 'scripts/**'
    - '.github/workflows/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: latest

    - name: Pack base asar
      run: |
        npm i -g asar
        sed -i -e "s/nightly/nightly-$(git rev-parse HEAD | cut -c 1-7)/" src/index.js
        node scripts/strip.js
        npx asar pack src app.asar

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-asar
        path: app.asar