name: Nightly

on:
  push:
    paths:
    - 'src/**'
    - 'scripts/**'
    - '.github/workflows/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3.6.0

    - name: Pack base asar
      run: |
        npm i -g @electron/asar
        sed -i -e "s/nightly/nightly-$(git rev-parse HEAD | cut -c 1-7)/" src/index.js
        node scripts/strip.js
        npx asar pack src app.asar

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: built-asar
        path: app.asar
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: 0.0.263-${{ github.workspace }}
        files: app.asar
